### ISSUE TITLE
.travis.yml still required?

### ISSUE THREAD

**Issue by docstun** [phrase/phrase-ruby#1]
Is this still necessary? Don't see anything related to Travis any more.

**Comment by docstun** [comment]
@rlisowski ping?

**Comment by rlisowski** [comment]
It’s autogenerated. There is no harm in keeping it.

**Comment by docstun** [comment]
I think it's misleading if we're not using Travis CI for this repo and thus it should be removed :)

**Comment by docstun** [comment]
Solved, closed.
