### ISSUE TITLE
locale_download not working

### ISSUE THREAD

**Issue by kroussevrb** [phrase/phrase-ruby#7]
This code

```
parameters = PhraseApp::RequestParams::LocaleDownloadParams.new(
    branch: branch_name,
    file_format: 'strings',
    encoding: 'UTF-8'
)
translations, error = phrase_app_client.locale_download project_id, 'fr', parameters
```

was refactored to:

```
translations = Phrase::LocalesApi.new.locale_download(
          project_id,
          'fr',
          { branch: branch_name, file_format: 'strings', encoding: 'UTF-8' }
        )
pp translations.inspect
```

And it prints 

`"#<Phrase::Response:0x00007fc81ac6cc50 @data=nil, @paginated=false, @next_page=nil>"`

no error

**Comment by kroussevrb** [comment]
By enabling debugging, I just found out that the HTTP response body contains the translations, but the response object is as shown above. How do I get a hold of the translations in this case?

**Comment by kroussevrb** [comment]
I was able to get it to return the translations in the response's `data` parameter by passing `return_type: 'String'` to `opts`, but I am not sure I should have to do this and I am not sure the returned string is deserialized correctly?

<img width="1152" alt="Screen Shot 2021-01-11 at 17 16 40" src="https://user-images.githubusercontent.com/17250295/104200112-ec9fef80-5430-11eb-9460-0cfc77bb5593.png">

**Comment by kroussevrb** [comment]
I checked with the `phraseapp-ruby` gem implementation and it seems that there the returned data looks the same way, so this will work for me. However, if `return_type` is really needed, it should be documented. Or the `download locale with http whatever` method should pass it to api client.

**Comment by kroussevrb** [comment]
Same problem in `branches_compare` with the same fix.

**Comment by theSoenke** [comment]
@kroussevrb Thanks a lot for taking a closer look at the issue. The solution with the `return_type` is definitely not great and not documented. We're are taking a closer look at this how to handle this in a better way

**Comment by theSoenke** [comment]
@kroussevrb We released a new major version of the library 2.0.0, which will always return a `File` object. Passing in the `return_type` is no longer necessary and this will also ensure that the return value will work with binary export formats.

**Comment by kroussevrb** [comment]
Thank you very much!

**Comment by kroussevrb** [comment]
@theSoenke does the same thing apply to `branch_compare` where I also had to apply the same `return_type: String` hack?
`response = Phrase::BranchesApi.new.branch_compare project_id, branch_name, { return_type: 'String' }`

**Comment by theSoenke** [comment]
@kroussevrb Unfortunately this is a separate issue and we're tracking this now internally. I hope that we also have a solution for that soon too.
