### ISSUE TITLE
Deployment pipelines have failed 

### ISSUE THREAD

**Issue by kronenthaler** [phrase/phrase-ruby#9]
Since version 2.8.4, the deployment pipeline has [failed](https://github.com/phrase/phrase-ruby/actions) and the latest versions (2.8.4, 2.8.5, 2.8.6, 2.8.7) are not available in rubygems.org

Can you republish those tags or publish a new one?

**Comment by jablan** [comment]
@kronenthaler thanks for the heads up! I re-tagged the 2.8.7 with the fixed GH action and it is on rubygems now.
